version: '3.9'
 
services:
    database_pokemon_digimon:
      image: mysql:5.7

      container_name: database_pd

      environment:
        MYSQL_ROOT_PASSWORD: '${PASS_PROD}'
        MYSQL_DATABASE: '${DB_PROD}'
        MYSQL_USER: '${USER_PROD}'
        MYSQL_PASSWORD: '${PASS_PROD}'

      ports:
        - "3306:3306"
 
      volumes:
        - 'dbdata:/var/lib/mysql'
  
      networks:
       - network_pd

    backend_pokemon_digimon:
      container_name: backend_pd
      build:
        context: .
        dockerfile: Dockerfile  
      command:
          yarn start
      volumes:
          - /usr/app      
      ports:
        - "3000:3333"  
      networks:
        - network_pd  
      depends_on:
          - database_pokemon_digimon
      mem_limit: 500m
      
volumes:
  dbdata:
    driver: local
networks:
  network_pd: 
    driver: bridge