version: '3.9'
 
services:
    database_pokemon_digimon_test:
      image: mariadb
      container_name: database_pokemon_digimon_test
      environment:
        MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD_TEST}'
        MYSQL_DATABASE: '${DATABASE_NAME_TEST}'
        MYSQL_USER: '${DATABASE_USERNAME_TEST}'
        MYSQL_PASSWORD: '${DATABASE_PASSWORD_TEST}'
      ports:
        - "${DATABASE_PORT_TEST}:3306" 
      volumes:
        - 'dbdatateste:/var/lib/mysql'  
      networks:
       - network_pokemon_digimon    
    database_pokemon_digimon:
      image: mariadb
      container_name: database_pokemon_digimon
      environment:
        MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
        MYSQL_DATABASE: '${DATABASE_NAME}'
        MYSQL_USER: '${DATABASE_USERNAME}'
        MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      ports:
        - "${DATABASE_PORT}:3306" 
      volumes:
        - 'dbdata:/var/lib/mysql'  
      networks:
       - network_pokemon_digimon
    backend_pokemon_digimon:
      container_name: backend_pokemon_digimon
      build:
        context: .
        dockerfile: Dockerfile  
      command:
          yarn start
      volumes:
          - /usr/app      
      ports:
        - "3000:3333"  
      networks:
        - network_pokemon_digimon  
      depends_on:
          - database_pokemon_digimon
      mem_limit: 500m
      
volumes:
  dbdata:
    driver: local
  dbdatateste:
    driver: local
networks:
  network_pokemon_digimon: 
    driver: bridge