version: '3.9'
 
services:
    database:
      image: mysql:5.7

      container_name: api_database

      environment:
        MYSQL_ROOT_PASSWORD: '${PASS_PROD}'
        MYSQL_DATABASE: '${DB_PROD}'
        MYSQL_USER: '${USER_PROD}'
        MYSQL_PASSWORD: '${PASS_PROD}'

      ports:
        - "3306:3306"
 
      volumes:
        - 'dbdata:/var/lib/mysql'
  
      networks:
       - mysql_network

    api_rest:
      container_name: api_rest
      build:
        context: .
        dockerfile: Dockerfile  
      command:
          yarn start
      volumes:
          - .:/usr/app      
      ports:
        - "3000:3333"  
      environment:
        NODE_ENV: 'prod'  
      networks:
        - mysql_network  
    #   depends_on:
    #       - database
      mem_limit: 500m
      
volumes:
  dbdata:
    driver: local
networks:
  mysql_network: 
    driver: bridge